# Generated by Django 4.1.4 on 2023-06-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_bookings_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookings",
            name="status",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
