# Generated by Django 4.1.4 on 2023-06-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_bookings_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookings",
            name="status",
            field=models.CharField(default="pending", max_length=1000),
        ),
    ]
